sudo: false
language: python
python:
  - '2.7'
  - '3.4'
env:
  - DJANGO=1.6.10 DB=postgres
  - DJANGO=1.7.7 DB=postgres
install:
  - pip install -q coverage flake8 psycopg2 Django==$DJANGO
before_script:
  - flake8 .
  - psql -c 'CREATE DATABASE entity;' -U postgres
script:
  - coverage run setup.py test
  - coverage report --fail-under=100
